### ISSUE TITLE
Zed Command should allow the use of custom CA Certificates

### ISSUE THREAD

**Issue by GauntletWizard** [authzed/zed#161]
The zed command currently only uses the system certificate store; However, it's easy enough under the authzed operator to use an internal CA to sign serving certificates. It would be helpful to be able to debug those with the standard zed command.

**Comment by jzelinskie** [comment]
zed will use your system certs -- you could add the CA certificate for your cluster there now.

Do you think it'd make sense to store certificates for each context or have folks specify them each time?

**Comment by GauntletWizard** [comment]
I'm a proponent of per-context; I anticipate you'll want "local", "dev" and "prod" contexts in many cases.

IT Policy explicitly prohibits adding the dev certs to system cert store at most companies I've worked with.

**Comment by jzelinskie** [comment]
Fixed in #183
