### ISSUE TITLE
first app shell tutorial fails in "zed permission check" step

### ISSUE THREAD

**Issue by ensonic** [authzed/zed#169]
The last part in https://docs.authzed.com/guides/first-app suggests to run 4 command like
```
zed permission check blog/post:1 read  blog/user:emilia --revision "${ZEDTOKEN}" # true
```
I take that I am suppose to use the taken here as revision (which I did). I am running a local SpiceDB instance (in minikube).

For the above command I get this error:
```
Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.9.1:50053: connect: connection refused"
Usage:
  zed permission check <resource:id> <permission> <subject:id> [flags]
...
```

The other terminal running the `kubectl port-forward` shows that it handled a connection attempt.

Versions:
```
zed --skip-version-check version
client: zed 0.7.5
service: v1.11.0
```

Also other commands do work:
```
zed relationship read 'blog/post'
blog/post:1 reader blog/user:beatrice
blog/post:1 writer blog/user:emilia
```

**Comment by ensonic** [comment]
Okay, this is not an issue in the `zed` util. Also tried the go-lang version of the tutorial and get the same error in this step too.

**Comment by ensonic** [comment]
t tries to connect to a second port:
```
kubectl port-forward deployment/dev-spicedb 50051:50051
# in the example "localhost:50051"
go run check.go
2022/11/17 12:51:41 failed to check permission: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.9.1:50053: connect: connection refused"
```
notice the `192.168.9.1:50053`

**Comment by josephschorr** [comment]
The error around port `50053` indicates that the system is trying to dispatch to other nodes within the cluster, but is failing to do so. I suspect your cluster is misconfigured for dispatch. How are you deploying the nodes within Kub?

**Comment by ensonic** [comment]
I used the spicedb-operator according to the instructions from
https://docs.authzed.com/spicedb/operator

**Comment by ensonic** [comment]
With some help from discord, I updated to 1.15.0 and still get the same error. Next we disabled dispatch in the config:
```
spec:
  config:
    datastoreEngine: memory
    image: authzed/spicedb:v1.15.0
    dispatchUpstreamAddr: ""
```
but still get the error.

**Comment by ensonic** [comment]
See https://github.com/authzed/spicedb-operator/issues/111

**Comment by vroldanbet** [comment]
@ensonic I'd suggest closing this issue as it's not a problem specific to zed, but a problem with the operator.

**Comment by ensonic** [comment]
Makes sense.

**Comment by vroldanbet** [comment]
Fix for problem here reported at https://github.com/authzed/spicedb-operator/pull/112
