### ISSUE TITLE
Default Endpoint Fails due to Missing Port

### ISSUE THREAD

**Issue by alecmerdler** [authzed/zed#2]
The default Authzed endpoint should include the port, otherwise it fails:
```sh
$ ./zed describe skynet_dev
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup grpc.authzed.com: no such host"
```

It should be configured to use `grpc.authzed.com:443` by default.

**Comment by jzelinskie** [comment]
We determined that this was just a transient DNS problem and that there was no issue with the port.
