### ISSUE TITLE
Exporting schema and relationships in a format that is compatible with zed import

### ISSUE THREAD

**Issue by corkrean** [authzed/zed#213]
If a user wishes to quickly transition permission systems, they will have to read their relationships and transform that data into an acceptable format for `zed import`.  It would be nice if the data could be exported with a single command in a format that is compatible with `zed import`.

There may need to be a warning with the export command because it could cripple performance when exporting large datasets.

**Comment by josephschorr** [comment]
We now have the `zed backup` experimental commands that, while not compatible with `zed import`, does allow for importing itself in a much more scalable format
