### ISSUE TITLE
Validate `.zaml` file should support sourcing schema from a file

### ISSUE THREAD

**Issue by tadejsv** [authzed/zed#287]
Right now you need to copy/paste the schema from the `zed` file to `.zaml` file for validation. I would like there to be an option to just put the name of the file for the `schema:` key - that way I can avoid duplicating code.

**Comment by epbensimpson** [comment]
As a workaround you can leave the schema empty (or leave it out altogether) and use something like `yq` to populate it:

```sh
yq '.schema = loadstr("schema.zed")' test_data.zaml > output.zaml

zed validate output.zaml
```
