### ISSUE TITLE
zed command relationship read, could not use the subject option without giving the relation option

### ISSUE THREAD

**Issue by Premsankar-Incresco** [authzed/zed#306]
zed relationship read <resource_type:optional_resource_id> <optional_relation> <optional_subject_type:optional_subject_id#optional_subject_relation> [flags]

could not pass  <optional_subject_type:optional_subject_id#optional_subject_relation> without passing the <optional_relation>

**Comment by josephschorr** [comment]
This can be done via the `--subject-filter` flag
