### ISSUE TITLE
Support command shorthands

### ISSUE THREAD

**Issue by bart1024** [authzed/zed#372]
It's a common practice for a CLI tool to support shorthands, e.g. `kubectl get services` is the same as `kubectl get svc`, `nats context` is the same as `nats ctx` and so on. 

It'd be nice for `zed` to support shorthands as well, so `zed permission` can be just `zed perm` for example.

**Comment by jzelinskie** [comment]
I think this is as simple as filling out the Alias field in the corresponding `cobra.Command`. Seems like a great first issue (once all the shorthand names have been bikeshedded 🤣)
