### ISSUE TITLE
release 0.21.2 contains no binaries/release action is invalid

### ISSUE THREAD

**Issue by Panaetius** [authzed/zed#418]
The release pipeline has failed and the latest github release does not contain a binary payload
https://github.com/authzed/zed/actions/runs/10938162375 seems github does not allow yaml anchors in actions files
```
Invalid workflow file: .github/workflows/release.yaml#L1
The workflow is not valid. .github/workflows/release.yaml: Anchors are not currently supported. 
Remove the anchor 'goreleaser_version'
```
and there's no binaries in https://github.com/authzed/zed/releases/tag/v0.21.2

We use this repo in a devcontainer feature to install zed
```
		"ghcr.io/devcontainers-contrib/features/gh-release:1": {
			"repo": "authzed/zed",
			"binaryNames": "zed"
		},
```
and this currently causes the devcontainer build to fail.

**Comment by tstirrat15** [comment]
That's frustrating about the anchors. I'll get that fixed and cut a release.

**Comment by Panaetius** [comment]
thank you!
